name: 'build-test'
on:
  push:
    branches: ["submission-*"]
env:
  OPENAI_ACCESS_TOKEN: ${{ secrets.OPENAI_ACCESS_TOKEN }}
  OPENAI_ORGANIZATION_ID: ${{ secrets.OPENAI_ORGANIZATION_ID }}
jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pupilfirst/ai-review-action@v1
        id: hello
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.result }}"
