name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"
env:
  OPENAI_ACCESS_TOKEN: ${{ secrets.OPENAI_ACCESS_TOKEN }}
  OPENAI_ORGANIZATION_ID: ${{ secrets.OPENAI_ORGANIZATION_ID }}
  REVIEW_BOT_USER_TOKEN: ${{ secrets.REVIEW_BOT_USER_TOKEN }}
  REVIEW_END_POINT: ${{ secrets.REVIEW_END_POINT }}
jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install graphql -v 2.0.27
          gem install ruby-openai dotenv pry graphql-client

      - name: Create JSON input file
        run: |
          echo '{
            "ROLE_PROMPT": "You are an advanced English Language Teaching Assistant AI. Your task involves reviewing and providing feedback on student submissions, paying meticulous attention to grammar, punctuation, and style errors.",
            "USER_PROMPT": "The conversation should include the following:\n- The specific Discord channel the conversation takes place in.\n- The initial question, marked with \"Student: \", outlining the student\'s doubt.\n- The instructor\'s response, labelled with \"Instructor: \", that provides a solution.\n- A follow-up question for clarification, again starting with \"Student: \", to delve into what the instructor meant.\n\nEnsure that the student applies the lessons they learned in the current level:\n- Provide context, steps taken, and error messages for both the initial question and the follow-up.\n- Frame questions around the \"why\" and \"how\" aspects.\n- Ask for additional examples, if necessary.\n- Thank the instructor in a proper and considerate manner.\n\nThe feedback should focus on the following areas (with the ideal condition in brackets):\n1. Providing Context & Background (The student delivers clear and detailed context, steps taken, and error messages).\n2. Clarity (The conversation is clear and easy to understand throughout).\n3. Expressing Thanks (The student thanks the instructor genuinely and appropriately).\n4. Appropriate Tone & Etiquette (The student maintains a professional and respectful tone throughout the conversation).\n\nMake sure to identify and highlight all grammar, punctuation, and style errors.\n\nThe student\'s submission will be as follows:\n\n${SUBMISSION}",
          }' > prompts.json

      - name: Run the ruby script
        run: ruby ./entrypoint.rb
